spring.application.name=moneytracker

# Config url-default
app.url=http://localhost:8080


# Config database
spring.datasource.url=jdbc:postgresql://localhost:5432/moneytracker_cloud
spring.datasource.username=postgres
spring.datasource.password=admin

# Đổi sang 'none' hoặc 'validate' vì đã có schema sẵn
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true


# Config JWT
security.jwt.secret=TUMROYALHELLOWORLD123123456456123123123123213123213213123123213213111111
security.jwt.expiration=86400000


# Config email (SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyenkimngoctum@gmail.com
spring.mail.password=zoqs imtt nijw dtqp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true