spring.application.name=moneytracker

# Config url-default
app.url=http://localhost:8080


# Config database
spring.datasource.url=jdbc:postgresql://localhost:5432/MoneyTracker
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Config JWT
security.jwt.secret=TUM_ROYAL_HELLO_WORLD_123123_456456_123123123123213123213213123123213213
security.jwt.expiration=86400000


# Config email (SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyenkimngoctum@gmail.com
spring.mail.password=zoqs imtt nijw dtqp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true